### ISSUE TITLE
Install help

### ISSUE THREAD

**Issue by drpedapati** [melff/RKernel#1]
This seems like a gem of a package - any suggestions on installations? my standard `devtools::install_github("melff/RKernel")` isn't doing the trick. Is there similar step as IRKernel to R -e 'IRkernel::installspec()' to add it to the Python environment? Thanks

**Comment by melff** [comment]
`devtools::install_github("melff/RKernel/pkg")` and then `RKernel::installspec()` should do the trick. The latter will install two variants of the kernel, one being a "regular" one and another where environment variables set such that openblas and gotoblas are run single-threaded. These single-threaded BLAS variants should be used if you have code that uses package "parallel" or similar parallel processing packages.

**Comment by amunizp** [comment]
```
> devtools::install_github("melff/RKernel/pkg")
Downloading GitHub repo melff/RKernel@HEAD
── R CMD build ─────────────────────────────────────────────────────────────────
   checking for file ‘/tmp/Rtmppl9PJB/remotes21f63dfb86b7/melff-RKernel-56b54cb/✔  checking for file ‘/tmp/Rtmppl9PJB/remotes21f63dfb86b7/melff-RKernel-56b54cb/pkg/DESCRIPTION’
─  preparing ‘RKernel’:
✔  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘RKernel_0.5.tar.gz’
   
Installing package into ‘/home/andres/R/x86_64-pc-linux-gnu-library/3.6’
(as ‘lib’ is unspecified)
* installing *source* package ‘RKernel’ ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
Error in as.Date.numeric(integer(0)) : 'origin' must be supplied
Error: unable to load R code in package ‘RKernel’
Execution halted
ERROR: lazy loading failed for package ‘RKernel’
* removing ‘/home/andres/R/x86_64-pc-linux-gnu-library/3.6/RKernel’
Warning message:
In i.p(...) :
  installation of package ‘/tmp/Rtmppl9PJB/file21f6800f0a1/RKernel_0.5.tar.gz’ had non-zero exit status

```

Sorry wondering if @drpedapati had the same issue as me? 

Maybe it is missing something like: origin = "1970-01-01" which I assume has to be wrong I would guess it would just choose some default start date?

**Comment by melff** [comment]
Which R version are you using? Any newer than version 4.3.2? I ask because I cannot reproduce the error on my system (which runs R 4.3.2),

**Comment by melff** [comment]
I could not reproduce the error that you show even with the development version of R (4.4.0). Are you using an old version of R? Could you please show the resuls of `sessionInfo()`?

Anyway, I suspect that this error should not show up with a recent R version, since then the "numeric" method of `as.Date()` uses `origin = "1970-01-01"` as default value.

**Comment by amunizp** [comment]
Thanks for reaching out so quickly.  I believe I ended up running the following: https://irkernel.github.io/ 
and it is now working my current R version is R version 3.6.3 (2020-02-29)

I was going blind for a while so it could be a misconfiguration in my machine.

**Comment by melff** [comment]
Your R version is very old, so this seems to be the root of the problem.
