### ISSUE TITLE
I wonder if the author is thinking about adding a rich color scheme of keywords and symbols similar to Rstudio, as well as output formatting?

### ISSUE THREAD

**Issue by antecede** [melff/RKernel#2]
Thanks to the author for a great job! The supported versions and features are also very new!
I wonder if the author is thinking about adding a rich color scheme of keywords and symbols similar to Rstudio, as well as output formatting?

For example, the keyword `library`
* Rstudio
![image](https://github.com/melff/RKernel/assets/46232487/695f7429-fa52-4bdb-be0d-d417fc568329)

* RKernel
![image](https://github.com/melff/RKernel/assets/46232487/d443cb9c-0e45-417f-93ff-97ce4711b6a8)

**Comment by antecede** [comment]
Besides, may I ask the author: Is there any parameter that can be controlled for the problem of text overlap in drawing? The same code will display better in R NoteBook. This code has been shown above.

* RKernel
![image](https://github.com/melff/RKernel/assets/46232487/487ab12d-ff25-410b-b207-a56bf85ce8e0)

* Rstudio `R notebook`
![image](https://github.com/melff/RKernel/assets/46232487/7a07d74b-c32b-4be4-a1aa-a409ab7bf3e4)

**Comment by melff** [comment]
> I wonder if the author is thinking about adding a rich color scheme of keywords and symbols similar to Rstudio, as well as output formatting?
> 

As far as I know, the syntax highlighting is provided by the Jupyter frontend and relies on a specific JavaScript library. The documentation about writing kernels for Jupyter unfortunately does not say anything about how this can be modified. If you find information on how to do this, I would be happy to look into it.

**Comment by melff** [comment]
> Besides, may I ask the author: Is there any parameter that can be controlled for the problem of text overlap in drawing?

You can change the width and height of graphics output using the options "jupyter.plot.width" and "jupyter.plot.height". So you can try to insert `options(jupyter.plot.width=10)` or something like it into your code.

In recent revisions, there is also the possibility to temporally set the plot width using a "magical comment" `#opt+:jupyter.plot.width=10`.

This of course needs documentation, which requires me to find the time for it ...

**Comment by antecede** [comment]
> > I wonder if the author is thinking about adding a rich color scheme of keywords and symbols similar to Rstudio, as well as output formatting?
> 
> As far as I know, the syntax highlighting is provided by the Jupyter frontend and relies on a specific JavaScript library. The documentation about writing kernels for Jupyter unfortunately does not say anything about how this can be modified. If you find information on how to do this, I would be happy to look into it.

Thank you for your prompt reply! Previously, while reviewing the IRKernel source code, I found some clues related to codemirror, but I am not very familiar with it, so I am not sure if it is directly related. If I encounter any related content in the future, I will come back and let you know.

**Comment by antecede** [comment]
> > Besides, may I ask the author: Is there any parameter that can be controlled for the problem of text overlap in drawing?
> 
> You can change the width and height of graphics output using the options "jupyter.plot.width" and "jupyter.plot.height". So you can try to insert or something like it into your code.`options(jupyter.plot.width=10)`
> 
> In recent revisions, there is also the possibility to temporally set the plot width using a "magical comment" .`#opt+:jupyter.plot.width=10`
> 
> This of course needs documentation, which requires me to find the time for it ...

Thank you for this kind reminder! I have learned about this method before, and it is currently the only way I know. One attractive aspect of R NoteBook is that it is adaptively adjusted based on images. If there is no better adaptive method, the current method can still solve the problem.

**Comment by melff** [comment]
> One attractive aspect of R NoteBook is that it is adaptively adjusted based on images.

Sorry, what software are you referring to with "R Notebook"? or do you mean "RStudio"?

**Comment by antecede** [comment]
> > One attractive aspect of R NoteBook is that it is adaptively adjusted based on images.
> 
> Sorry, what software are you referring to with "R Notebook"? or do you mean "RStudio"?

Sorry for the confusion, yes, `R Notebook` in `RStudio`
