### ISSUE TITLE
Problem with a shared log file (/tmp/RKernel.log)

### ISSUE THREAD

**Issue by atadych** [melff/RKernel#3]
Thanks for this package. It worked well for me.

However when more than 1 person installs this package on the same remote server then there is a problem with a shared log file ( `/tmp/RKernel.log`) and the second person can't start jupyter notebook with Rkernel.

There should be a way to define a different log for each person. Right now it seems that [the path to  the logfile is hardcoded: ](https://github.com/melff/RKernel/blob/main/pkg/R/utils.R#L28)
`log_fn <- "/tmp/RKernel.log"`

**Comment by melff** [comment]
Changed this to `log_fn <- file.path(tempdir(),"RKernel.log")`, this should give a different log for each user.

It should work now for you. If it does not, please let me know.

**Comment by atadych** [comment]
It works! Thanks for fixing it.
